server:
  port:8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todolist?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: seyun
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
